language: java

env:
  global:
    - CC_TEST_REPORTER_ID=d0b85a1fa61a2d91971a77a3c270f648a2428177c57f084bd0c944dc134d8139

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
