/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package percolation;

import org.testng.annotations.*;
import static org.testng.Assert.*;
import percolation.Percolation;

public class PercolationTest {
    @Test public void percolatesForGivenData() {
        Percolation pc = new Percolation(2);
        pc.open(1,1);
        pc.open(2,2);
        pc.open(1,2);
        assertEquals(pc.percolates(), true);
    }
}
